### PR TITLE
Add support for invisible recaptcha and when prototypejs is not yet loaded

### PR DESCRIPTION
**Pull request by pimdebrabander**

### CODE REVIEW

**Comment by ProxiBlue** [comment]
Sorry man, been a bit busy. Will pull changes down today and test.

**Comment by vishy93** [comment]
@ProxiBlue it is all good. I am excited to try this out soon.

**Comment by m-overlund** [comment]
It seems to suppress error messages.
I couldn't submit the forms after updating, due to new api keys needs to be generated to support Invisible reCaptha.

This error was only visible in the code and not on frontend.

**Comment by ProxiBlue** [comment]
Yes, I noticed that also. I am reworking the functionality so a new set of api key section is to be used for invisible. 

May sound strange, but not everyone wants invisible, so I want to keep I am not a robot as an option.

**Comment by ProxiBlue** [comment]
Hi, refer to branch: https://github.com/ProxiBlue/reCaptcha/tree/wip-invisible

This is using code from this PR, but adjusted to allow selection of either: core captcha (yes, in case google captcha goes offline, there is a fall-back), 'I am not a robot' and Invisible

I have not tested fully (this was done late last night), but prelimanary usage on account create/login worked.

Admin invisible is not working (can get to that later today)

I created a new ticket (see issues) where you can place any feedback.

Some testing and initial usage / thoughts appreciated. Do not use in production.

**Comment by ProxiBlue** [comment]
@m-overlund @vishy93 @pimdebrabander 

Check branch wip-invisible - now also has working admin invisible
I need to test all areas which will follow soon, but if you have time, and can test areas, feedback in previous noted ticket what works will be appreciated.

**Comment by vishy93** [comment]
@ProxiBlue Looks to be working okay thus far, stupid question but how can I trigger the actual captcha?

**Comment by ProxiBlue** [comment]
@pimdebrabander 

I reverted this merge, as I have determined that the code which intercepts the form submit does not in fact intercept the submit on onepage checkout login, so invisible recaptcha is not in fact functional on checkout.

```
 form.addEventListener('submit', function(e) {
                            e.preventDefault();
                            if (varienForm.validator.validate()) {
                                grecaptcha.execute(elm);
                            }
                        });
```
Since persons could be using dev-master in their composer configs, they woudl pull in broken recaptcha

I am busy adjusting this module to work with invisible in all areas on branch wip-invisible, which also allows the choice of non invisible

**Pull request merged**
