### PR TITLE
Supports CURL for google recaptcha requests

### PR DESCRIPTION
**Pull request by jonshipman**
Had a problem on magento 1.9 where google wouldn't connect using the standard Zend_Http_Client. Setting this adapter allows the request to go through.

### CODE REVIEW

**Comment by ProxiBlue** [comment]
Hello.

Interesting. Any details on exactly what error was?
I would prefer this to be an option rather to becone the default as yours
is the only issue that rewuires curl and this could again cause the
majority to have connection problems.

If you can please add a config option and code to effect the curl adapter
if so set.

This way the normal usage as has been continues and curl can be enabled if
anyone else ever so require.

**Comment by jonshipman** [comment]
`Form ID: backend_login=>Exception fail : Unable to Connect to ssl://www.google.com:443. Error #110: Connection timed out`

See [https://stackoverflow.com/questions/10817821/zend-http-client-timed-out](https://stackoverflow.com/questions/10817821/zend-http-client-timed-out)

From the best that I can guess, it might be the lack of ipv6 on our server. 

I'll see about adding the config option. And update the PR here.

**Comment by jonshipman** [comment]
Added the adapter as a config option. 

I've confirmed openssl is loaded via phpinfo. Probably comes down to the socket not downgrading to ipv4 when the host itself only has an ipv4 address.

**Comment by ProxiBlue** [comment]
New release created: https://github.com/ProxiBlue/reCaptcha/releases/tag/2.5.0

**Pull request merged**
